name: Check

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '2 3 * * 3'
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run jabref-action
        uses: jabref/jabref-action@main
        with:
          bibfile: chocolate/Chocolate.bib
